In [82]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [83]:
import torch
from torch.nn import Embedding

In [84]:
n_embeddings, dim = 10, 4

In [85]:
emb_1 = Embedding(n_embeddings, dim)

In [86]:
emb_1.weight

Parameter containing:
tensor([[-0.0770,  1.3486, -0.3189, -1.1807],
        [ 1.7422, -1.2712, -0.8330, -0.2070],
        [-2.6928,  0.3090,  0.0377, -0.2534],
        [-0.4828,  0.8266,  0.2567,  1.7748],
        [-0.1075, -0.4203, -0.6300,  0.4063],
        [-1.5217,  0.1617,  0.1653, -0.5060],
        [-0.7145, -0.8803, -1.0185, -0.9204],
        [-0.1019, -1.8421, -0.8073,  0.7060],
        [-1.9837, -1.4528,  0.9617,  2.1742],
        [-0.3916,  0.0729,  1.1836,  0.4746]], requires_grad=True)

In [96]:
inp = torch.LongTensor([[0, 1, 2]])
emb_1(inp)

tensor([[[-0.0770,  1.3486, -0.3189, -1.1807],
         [ 1.7422, -1.2712, -0.8330, -0.2070],
         [-2.6928,  0.3090,  0.0377, -0.2534]]], grad_fn=<EmbeddingBackward0>)

In [88]:
inp = torch.LongTensor([[0, 1, 2, 3]])
emb_1(inp)

tensor([[[-0.0770,  1.3486, -0.3189, -1.1807],
         [ 1.7422, -1.2712, -0.8330, -0.2070],
         [-2.6928,  0.3090,  0.0377, -0.2534],
         [-0.4828,  0.8266,  0.2567,  1.7748]]], grad_fn=<EmbeddingBackward0>)

In [89]:
emb_2 = Embedding(n_embeddings, dim, padding_idx=5)

In [90]:
emb_2.weight

Parameter containing:
tensor([[ 0.5342,  0.8960, -1.8306,  0.4651],
        [-0.3878,  0.7986, -2.1576,  0.5118],
        [-1.5801,  1.8827, -0.9997, -1.2748],
        [ 1.0436,  0.6020,  0.0472, -0.1841],
        [-1.9764, -0.7421, -0.7065,  0.3342],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [-1.0429, -1.2013, -0.7404,  1.5183],
        [ 1.4581, -0.3934, -0.5161,  1.0336],
        [-0.4387, -1.6046,  1.8560, -0.0855],
        [ 0.9010, -1.4010, -0.9526,  0.1447]], requires_grad=True)

In [91]:
emb_2(inp).mean().backward()

In [92]:
emb_2.weight.grad

tensor([[0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625],
        [0.0625, 0.0625, 0.0625, 0.0625],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [93]:
emb_3 = Embedding(n_embeddings, dim, norm_type=2, max_norm=1)

emb_3.weight

Parameter containing:
tensor([[ 1.3339, -1.1989,  0.3232, -0.8893],
        [ 1.1520,  0.1761, -0.6374, -0.8149],
        [ 0.7424, -1.3201, -1.1141, -0.0816],
        [-0.5057,  0.6614,  0.8398,  0.0943],
        [ 0.9928,  1.1355,  0.2883,  1.0416],
        [ 0.0840, -0.5667,  1.3190, -0.8033],
        [-0.7602,  1.2354,  0.5823, -1.0017],
        [-0.3659, -0.0274, -0.0758,  1.0487],
        [-0.9380,  1.2051, -0.3034, -0.3585],
        [ 0.3021,  1.1702, -0.2337, -0.9605]], requires_grad=True)

In [94]:
emb_3.weight.norm(dim=1)

tensor([2.0277, 1.5584, 1.8819, 1.1864, 1.8555, 1.6472, 1.8565, 1.1136, 1.5977,
        1.5614], grad_fn=<LinalgVectorNormBackward0>)

In [95]:
emb_3(inp).norm(dim=1)

tensor([[1.1474, 1.0794, 1.0219, 0.6885]], grad_fn=<LinalgVectorNormBackward0>)